### ISSUE TITLE
建议：请考虑减少使用pre-release功能，可能会造成刷屏 please consider not to use pre-release for your deployment to prevent spam

### ISSUE THREAD

**Issue by sunyong01** [work7z/LafTools#31]
每当一个beta版本号更新时，actions自动进行到pre- release，这会对关注了该项目的用户进行一次主页推送，当版本号更新频繁时，会造成刷屏
<img width="910" alt="image" src="https://github.com/work7z/LafTools/assets/43025602/019224f7-52d5-4277-8163-556675147263">

<img width="890" alt="image" src="https://github.com/work7z/LafTools/assets/43025602/22a85366-40dc-48c4-874c-fcfc68b7dd43">

**Comment by work7z** [comment]
好的，感谢反馈，实在抱歉有这个困扰，不是有意的。打pre-release只是为了部署到线上服务器，这边会及时改进的。在修复这个刷屏问题之前，暂时不推新的pre-release。

thanks for your feedback! I apologize for the issue, we didn't meant to make this happen. these pre-release were pushed for deployment only.  we would not be pushing any new pre-release before this issue is resolved.

**Comment by work7z** [comment]
感谢反馈和理解，此问题已修复，内部beta版本部署时将不会推送release信息。

thanks for your feedback and understanding, this issue has been resolved now. The release will be pushed to your timeline when our internal beta version is deployed.

**Comment by work7z** [comment]
目前将此issue关闭了哈，如果有其他任何情况请重新开启此issue，感谢!

I will close this issue now, kindly reopen this issue if there's any concern or issue, thanks!
